site_name: ORBITAL Documentation
site_url: https://orbital-assistive-tech.github.io/documentation/
nav:
- Welcome to ORBITAL Docs: index.md
- Project Overview: overview.md
- Sprint 1 - Spring '25:
  - Form-Factor - Mechanical Team: sprint_1_teams/form_factor.md
  - Cam Actuation Exploration - Mechanical Team: sprint_1_teams/cam_actuation.md
  - Firmware & Circuit Team: sprint_1_teams/firmware_circuit.md
  - Software & Embedded Systems Team: sprint_1_teams/software.md


docs_dir: docs/
extra_css:
  - style.css

theme:
  name: material
  palette:
    primary: blue

  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.expand # Automatically expand the current section
  - navigation.sections
  - navigation.path
  - navigation.prune
  - navigation.indexes
  - navigation.top
  - search.suggest
  plugins:
  - search
  markdown_extensions:
  - toc:
      permalink: true
      title: On this page
      toc_depth: 4

