site_name: ORBITAL Documentation
site_url: https://mydomain.org/mysite
nav:
- Welcome to Docs: index.md
- Project Overview: overview.md
- Sprint Reviews:
  - Sprint 1: sprint_1.md
  - Sprint 2: sprint_2.md

docs_dir: docs/
extra_css:
  - style.css

theme:
  name: material
  palette:
    primary: blue

  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.path
  - navigation.prune
  - navigation.indexes
  - navigation.top
  - search.suggest
  plugins:
  - search
  markdown_extensions:
  - toc:
      permalink: true
      title: On this page
      toc_depth: 4

